@extends('layouts.web')

@section('content')
    <div class="container">
        <div class="row">
            <div class="terms col-md-12">
                <h1>Termos de Serviço do Grupo Unika</h1>
                <span>Última modificação: 01 de setembro de 2016</span>
                <p>Agradecemos por usar nossos produtos e serviços ("Serviços"). Os Serviços serão fornecidos pelo Unika Consultoria e Informática Ltda 'razão social'. (“Grupo Unika 'nome fantasia' ”), localizado em Rua Alaor Prata, 362, Uberaba, Minas Gerais, Brasil.</p>
                <p>Ao usar nossos Serviços, você está concordando com estes termos. Leia-os com atenção.</p>
                <p>Nossos Serviços são muito diversos, portanto, às vezes, podem aplicar-se termos adicionais ou exigências de produtos (inclusive exigências de idade). Os termos adicionais estarão disponíveis com os Serviços relevantes e esses termos adicionais se tornarão parte de nosso contrato com você, caso você use esses Serviços.</p>
                <p>Se você estiver usando nossos Serviços em nome de uma organização, termos adicionais de contratos podem ser aplicados em um termo específico elaborado e concordado entre as partes, ao qual, sua empresa tem acesso.</p>
                <h2>Como usar nossos Serviços</h2>
                <p>É preciso que você siga as políticas disponibilizadas a você dentro dos Serviços.</p>
                <p>Não faça uso indevido de nossos Serviços. Por exemplo, não tente acessá-los por um método diferente da interface e das instruções que fornecemos. Você pode usar nossos serviços somente conforme permitido por lei. Podemos suspender ou deixar de fornecer nossos Serviços se você descumprir nossos termos ou políticas ou se estivermos investigando casos de suspeita de má conduta.</p>
                <p>O uso de nossos Serviços não lhe confere a propriedade sobre direitos de propriedade intelectual sobre os nossos Serviços ou sobre o conteúdo que você acessar. Você não pode usar conteúdos de nossos Serviços a menos que obtenha permissão do proprietário de tais conteúdos ou que o faça por algum meio permitido por lei. Estes termos não conferem a você o direito de usar quaisquer marcas ou logotipos utilizados em nossos Serviços. Não remova, oculte ou altere quaisquer avisos legais exibidos em ou junto a nossos Serviços.</p>
                <p>Nossos Serviços exibem alguns conteúdos que não são do Grupo Unika. Esses conteúdos são de exclusiva responsabilidade da entidade que os disponibiliza, como propagandas, por exemplo. Podemos revisar conteúdo para determinar se é ilegal ou se infringe nossas políticas, e podemos remover ou nos recusar a exibir conteúdos que razoavelmente acreditamos violar nossas políticas ou a lei. Mas isso não significa, necessariamente, que revisaremos conteúdos, portanto por favor, não presuma que o faremos.</p>
                <p>Em relação com seu uso dos Serviços, podemos enviar-lhe anúncios de serviços, mensagens administrativas e outras informações. Você pode desativar algumas dessas comunicações.</p>
                <p>Alguns dos nossos Serviços estão disponíveis em dispositivos móveis. O usuário não deve utilizar tais Serviços de forma que o distraia ou o impeça de cumprir leis de trânsito, de segurança ou mesmo do ambiente em que está.</p>
                <h2>Sua Conta no Grupo Unika</h2>
                <p>Talvez você precise criar uma Conta em algum dos Serviços do Grupo Unika para utilizar alguns dos nossos Serviços. Você poderá criar sua própria Conta no Grupo Unika ou sua Conta poderá ser atribuída a você por um administrador, como seu empregador ou instituição a que pertence. Se você estiver usando uma Conta do Grupo Unika atribuída a você por um administrador, termos diferentes ou adicionais podem aplicar-se e seu administrador poderá ser capaz de acessar ou desativar sua conta.</p>
                <p>Para proteger sua Conta no Grupo Unika, o usuário deve manter a senha em sigilo. A atividade realizada na Conta no Grupo Unika ou por seu intermédio é de responsabilidade do usuário. Não recomendamos que a senha da sua Conta seja reutilizada em aplicativos de terceiros. Caso tome conhecimento de uso não autorizado da sua senha ou Conta, entre em contato pelo e-mail abuse@gunika.co.</p>
                <h2>Seu Conteúdo em nossos Serviços</h2>
                <p>Alguns de nossos Serviços permitem que você faça upload, submeta, armazene, envie ou receba conteúdo (arquivos, fotos, texto etc). Você mantém a propriedade de quaisquer direitos de propriedade intelectual que você detenha sobre aquele conteúdo. Em resumo, aquilo que pertence a você, permanece com você.</p>
                <p>Quando você faz upload, submete, armazena, envia ou recebe conteúdo a nossos Serviços ou por meio deles, você concede ao Grupo Unika (e àqueles com quem trabalhamos) uma licença mundial para usar, hospedar, armazenar, reproduzir, modificar, criar obras derivadas, comunicar, publicar, executar e exibir publicamente e distribuir tal conteúdo. Os direitos que você concede nesta licença são para os fins restritos de operação, promoção e melhoria de nossos Serviços e de desenvolver novos Serviços. Essa licença perdura mesmo que você deixe de usar nossos Serviços (por exemplo, um cadastro de empresa que você fez no ESERV). Alguns Serviços podem oferecer-lhe modos de acessar e remover conteúdos que foram fornecidos para aquele Serviço. Além disso, em alguns de nossos Serviços, existem termos ou configurações que restringem o escopo de nosso uso do conteúdo enviado nesses Serviços. Certifique-se de que você tem os direitos necessários para nos conceder a licença de qualquer conteúdo que você enviar a nossos Serviços.</p>
                <p>Nossos sistemas automatizados analisam o seu conteúdo para fornecer recursos de produtos pessoalmente relevantes para você, como resultados de pesquisa customizados, propagandas personalizadas. Essa análise ocorre à medida que o conteúdo é enviado e recebido, e quando ele é armazenado.</p>
                <p>Se você enviar comentários ou sugestões sobre nossos Serviços, podemos usar seus comentários ou sugestões para melhorar nossos Serviços.</p>
                <h2>Como modificar e cancelar nossos Serviços</h2>
                <p>Estamos constantemente alterando e melhorando nossos Serviços. Podemos incluir ou remover funcionalidades ou recursos e podemos também suspender ou encerrar um Serviço por completo.</p>
                <h3>Nossas Garantias e Isenções de Responsabilidade</h3>
                <p>Fornecemos nossos Serviços usando um nível comercialmente razoável de capacidade e cuidado e esperamos que você aproveite seu uso deles. Mas existem algumas coisas que não prometemos sobre nossos Serviços.</p>
                <p>Exceto quando expressamente previsto nestes termos ou em termos adicionais, nem o Grupo Unika, nem seus fornecedores ou distribuidores oferecem quaisquer garantias sobre os Serviços. Por exemplo, não nos responsabilizamos pelos conteúdos nos Serviços (um local disponível ou não no Albook), disponibilidade ou capacidade de atender alguma necessidade específica. Fornecemos os serviços “na forma em que foram informados”.</p>
                <h2>Responsabilidade pelos nossos Serviços</h2>
                <p>Quando permitido por lei, o Grupo Unika e os fornecedores ou distribuidores do Grupo Unika não serão responsáveis por perda de lucros, perda de receita, perda de dados, perdas financeiras ou por danos indiretos, especiais, consequenciais, exemplares ou punitivos.</p>
                <p>Na medida permitida por lei, a responsabilidade total do Grupo Unika e de seus fornecedores e distribuidores, para qualquer reclamação sob estes termos, incluindo quaisquer garantias implícitas, limita-se ao valor que você pagou ao Grupo Unika para usar os Serviços (ou, a nosso critério, para fornecer a você os Serviços novamente).</p>
                <p>Em todos os casos, o Grupo Unika e seus fornecedores e distribuidores não serão responsáveis por qualquer perda ou dano que não seja razoavelmente previsível.</p>
                <h2>Usos comerciais de nossos Serviços</h2>
                <p>Se você estiver usando nossos Serviços em nome de uma organização, tal organização aceita estes termos. Ela isentará de responsabilidade e indenizará o Grupo Unika e suas afiliadas, executivos, agentes e trabalhadores de qualquer reivindicação, processo ou ação judicial proveniente de ou relacionado ao uso dos Serviços ou à violação destes termos, incluindo qualquer responsabilidade ou despesa resultante de reivindicações, perdas, danos, processos, julgamentos, custos de litígio e honorários advocatícios.</p>
                <h2>Sobre estes Termos</h2>
                <p>Podemos modificar estes termos ou quaisquer termos adicionais que sejam aplicáveis a um Serviço para, por exemplo, refletir alterações da lei ou mudanças em nossos Serviços. Você deve consultar os termosregularmente. Postaremos avisos sobre modificações nesses termos nesta página. Publicaremos um aviso de alteração sobre os termos adicionais dentro do Serviço aplicável. As alterações não serão aplicadas retroativamente e entrarão em vigor pelo menos quatorze dias após sua publicação. Entretanto, alterações a respeito de novas funcionalidades de um Serviço ou alterações feitas por razões legais entrarão em vigor imediatamente. Se você não concordar com os termos alterados de um Serviço, deve descontinuar o uso desse Serviço.</p>
                <p>Em caso de conflito entre estes termos e os termos adicionais, os termos adicionais prevalecerão com relação a esse conflito.</p>
                <p>Estes termos regem a relação entre o Grupo Unika e você. Eles não criam quaisquer direitos para terceiros.</p>
                <p>Caso você não cumpra estes termos e nós não tomemos providências imediatas, isso não significa que estamos renunciando a quaisquer direitos que possamos ter (como tomar providências futuras).</p>
                <p>Caso uma condição específica destes termos não seja executável, isso não prejudicará quaisquer outros termos.</p>
                <p>Nos outros casos todas as reclamações decorrentes de ou relacionadas com esses termos ou Serviços serão litigadas exclusivamente em tribunais estaduais ou federais da Comarca de Ubera, Minas Gerais, Brasil e você e o Grupo Unika autorizam a jurisdição pessoal nesses tribunais.</p>
                <p>Para obter informações contate-nos em contato@gunika.co.</p>
            </div>
        </div>
    </div>
@endsection